module.exports = {
"armos" : "Hit it with a sword, and watch out for the fast ones.  Try arrows",
"blade trap" : "You cannot beat a blade trap.  Do your best to avoid them.  Try getting close to trigger them, then run through when they reset",
"boulder" : "You cannot beat a boulder.  Avoid them.",
"bubble" : "You cannot beat a bubble.  Avoid them or you lose your sword capability",
"darknut" : "You must attack from the side or back.  Try bombs",
"gel" : "Hit with your sword",
"ghini": "Hit with your sword.  Killing the original kills the rest.",
"gibdo" : "Hit with your sword.  Can be lit on fire to turn into Stalfos.",
"goriya": "Avoid the boomerang, and Hit it with your sword.",
"keese": "Hit it with your sword or boomerang",
"lanmola": "Hit it with your sword",
"leever": "Hit it with your sword when they come above ground",
"like like" : "Hit it with your sword.  Do not get eaten, or you will lose a shield",
"lynel" : "Avoid its attacks and Hit it with your swords.  Magical Shield will block projectiles.",
"moblin" : "Block arrows with your shield, and Hit it with your sword.",
"octorok" : "Block rocks with shield.  Hit it with your sword.",
"peahat" : "Wait until its stationary. Hit it with your sword.",
"pols voice" : "Shoot with arrows",
"river zora" : "Wait until it appears above water and Hit it with your sword.  Block fireballs with Magical shield.",
"rope" : "Hit it with your sword",
"stalfos" : "Hit it with your sword",
"tektite" : "Hit it with your sword",
"vire" : "Hit it with your sword",
"wallmaster" : "Keep your distance, and hit with your sword.",
"wizzrobe" : "Wait until they appear and hit with your sword.  Block beams with Magical Shield",
"zol": "Hit with your sword",
"aquamentus": "Avoid fireballs and hit the head",
"dodongo" :"Feed three bombs",
"manhandla" : "Hit leaves with sword, or use bombs",
"gleeok" : "Hit heads with swords.  Avoid floating heads",
"digdogger" : "Use the flute and then hit with your sword",
"gohma" : "Wait until the eye opens and shoot an arrow into the eye",
"gannon" : "Hit him with your sword until he changes color.  Then fire a silver arrow at him"
}
